#!/bin/sh
export USER=postgres
exec 2>&1 # pipe stderr to stdout
echo "STARTED SERVICE: postgresql-service"
## Add your service task command below
## Call your service with exec command
su - $USER -c "exec postgres -D /data > /log/postresql.log 2>&1"
